/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/man.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/man.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
        <primitive object={nodes.root} />
        <skinnedMesh geometry={nodes['caucasian-base'].geometry} material={materials.middleage_cauasian_male} skeleton={nodes['caucasian-base'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-eyebrow001'].geometry} material={materials.eyebrow001} skeleton={nodes['caucasian-eyebrow001'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-low_poly'].geometry} material={materials.Eye_brown} skeleton={nodes['caucasian-low_poly'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-male_casualsuit02'].geometry} material={materials.male_casualsuit02} skeleton={nodes['caucasian-male_casualsuit02'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-shoes02'].geometry} material={materials.Shoes02} skeleton={nodes['caucasian-shoes02'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-short04'].geometry} material={materials.short04} skeleton={nodes['caucasian-short04'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-teeth_base'].geometry} material={materials.teethMaterial} skeleton={nodes['caucasian-teeth_base'].skeleton} />
        <skinnedMesh geometry={nodes['caucasian-tongue01'].geometry} material={materials.tongue01Material} skeleton={nodes['caucasian-tongue01'].skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/man.glb')
